apiVersion: v1
kind: Service

metadata:
  name: load-balancer
  labels:
    componente: load-balancer

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    tier: frontend
