apiVersion: apps/v1
kind: Deployment

metadata:
  name: web

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: web
        image: davidelorza/labo8
        ports:
        - containerPort: 5000
